"""Database provider registry and base adapter types."""

from .adapters.base import ColumnInfo, DatabaseAdapter, TableInfo
from .exceptions import MissingDriverError
from .registry import (
    ProviderSpec,
    get_adapter,
    get_adapter_class,
    get_all_schemas,
    get_badge_label,
    get_connection_display_info,
    get_connection_schema,
    get_db_type_for_scheme,
    get_default_port,
    get_display_name,
    get_supported_db_types,
    get_supported_url_schemes,
    get_url_scheme_map,
    has_advanced_auth,
    is_file_based,
    normalize_connection_config,
    register_provider,
    requires_auth,
    requires_database_selection,
    supports_ssh,
    validate_database_required,
)
from .schema_catalog import ConnectionSchema, FieldType, SchemaField, SelectOption

__all__ = [
    "ColumnInfo",
    "DatabaseAdapter",
    "TableInfo",
    "MissingDriverError",
    "ProviderSpec",
    "ConnectionSchema",
    "FieldType",
    "SchemaField",
    "SelectOption",
    "get_adapter",
    "get_adapter_class",
    "get_all_schemas",
    "get_badge_label",
    "get_connection_display_info",
    "get_connection_schema",
    "get_db_type_for_scheme",
    "get_default_port",
    "get_display_name",
    "get_supported_db_types",
    "get_supported_url_schemes",
    "get_url_scheme_map",
    "has_advanced_auth",
    "is_file_based",
    "normalize_connection_config",
    "register_provider",
    "requires_auth",
    "requires_database_selection",
    "supports_ssh",
    "validate_database_required",
]
